AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Soccer analytics API and pipeline

Resources:
  SoccerAnalyticsApi:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  RawSnapshotsBucket:
    Type: AWS::S3::Bucket

  RefreshSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(15 minutes)
